version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  plugins = ["react"]
  style_guide = "google"

[[transformers]]
name = "prettier"
enabled = true
